name: veinmind-backdoor
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd veinmind-backdoor
          tar -cvzf veinmind-backdoor.tar.gz *
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-backdoor.tar.gz
          path: ./veinmind-backdoor/veinmind-backdoor.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-backdoor/veinmind-backdoor.tar.gz
  push-image:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: veinmind/veinmind-backdoor:latest
          context: ./veinmind-backdoor
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}

